title: "Manish Patil — AI / ML Engineer"
email: your.email@example.com
description: "Portfolio — projects, experiments, and blog about machine learning and AI."
baseurl: "" # leave empty for user.github.io
url: "https://Manya009.github.io" # replace
theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
  experiments:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
  - scope:
      path: ""
      type: "experiments"
    values:
      layout: project